name: Deploy to Azure Container App

on:
  push:
    branches:
    - mainx

env:
  UNIQUE_APP_NAME: comicdownorleans
  AZURE_RESOURCE_GROUP_NAME: comic-orleans
  AZURE_RESOURCE_GROUP_LOCATION: northeurope

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: .NET publish app
      run: dotnet publish ./comic-downloader-orleans.csproj --configuration Release

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Flex bicep
      run: |
        az deployment group create \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME }} \
          --template-file '.github/workflows/flex/main.bicep' \
          --parameters location=${{ env.AZURE_RESOURCE_GROUP_LOCATION }} \
            appName=${{ env.UNIQUE_APP_NAME }} \
            telegram_apikey=${{ secrets.TELEGRAM_APIKEY }} \
            onedrive_clientid=${{ secrets.ONEDRIVE_CLIENTID }} \
            vg_cookie=${{ secrets.VG_COOKIE }} \
          --debug

    - name: Prepare Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Silo image to dockerhub
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/comic:latest
        file: Dockerfile

    - name: Installing Container Apps extension
      uses: azure/cli@v1
      with:
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az extension add --name containerapp --yes

    - name: Deploy Silo
      uses: azure/cli@v1
      with:
        inlineScript: |
          az containerapp update -n ${{ env.UNIQUE_APP_NAME }} -g ${{ env.AZURE_RESOURCE_GROUP_NAME }} -i ${{ secrets.DOCKERHUB_USERNAME }}/comic:latest

    - name: Logout of Azure
      run: az logout
